/**
 * Default parameter values per section. Align with firmware defaults in
 * eepromhelper.cpp / globalincludes.h when updating.
 * Format: { param, value } for setParam, or { preset: true, param, value } for setPreset.
 */

export const SYSTEM_DEFAULTS = [
  { param: 'setdevicename', value: 'AmbiBack' },
  { param: 'setbuttonmode', value: 0 },
  { param: 'setwififail', value: 0 },
  { param: 'setdebugsyslogserver', value: '' },
  { param: 'setdebugsyslogport', value: 514 },
  { param: 'setdebugserial', value: 0 },
  { param: 'setdebugsyslog', value: 0 },
  { param: 'setdebugultra', value: 0 },
  { param: 'setwifiapenable', value: 0 },
  { param: 'setrelaymode', value: 1 },
  { param: 'setrelaytodirect', value: 0 },
  { param: 'setrelaywifidirect', value: 0 },
  { param: 'setcamautoonoff', value: 0 },
  { param: 'setcamautoonoffdelay', value: 15 },
]

export const LED_SETUP_DEFAULTS = [
  { param: 'setvertical', value: 18 },
  { param: 'sethorizontal', value: 32 },
  { param: 'setdirection', value: 1 },
  { param: 'setsidetop', value: 1 },
  { param: 'setsideleft', value: 1 },
  { param: 'setsideright', value: 1 },
  { param: 'setsidebottom', value: 1 },
  { param: 'settopbrightness', value: 100 },
  { param: 'setleftbrightness', value: 100 },
  { param: 'setrightbrightness', value: 100 },
  { param: 'setbottombrightness', value: 100 },
  { param: 'setcolorred', value: 255 },
  { param: 'setcolorgreen', value: 255 },
  { param: 'setcolorblue', value: 255 },
]

export const COLOR_MOTION_DEFAULTS = [
  { preset: true, param: 'setcolorpreset', value: 1 },
  { preset: true, param: 'setbrightnesspreset', value: 3 },
  { preset: true, param: 'setmotionpreset', value: 2 },
  { param: 'setcolorboost', value: 0 },
  { param: 'setcolorboostbalance', value: 50 },
  { param: 'setcolorboostmin', value: 0 },
  { param: 'setcolorboostred', value: 100 },
  { param: 'setcolorboostgreen', value: 100 },
  { param: 'setcolorboostblue', value: 100 },
  { param: 'setcolorboostthreshold', value: 0 },
  { param: 'setcolorvaluegain', value: 100 },
  { param: 'setbrightness', value: 255 },
  { param: 'setminimumluminosity', value: 0 },
  { param: 'setframesmoothing', value: 0 },
  { param: 'setframelength', value: 10 },
  { param: 'setframedelay', value: 40 },
]

export const AMBIENT_DEFAULTS = [
  { param: 'setambientpreset', value: 0 },
  { param: 'setambientspeed', value: 5 },
  { param: 'setambientintensity', value: 80 },
]

export const CAMERA_DEFAULTS = [
  { preset: true, param: 'setcampreset', value: 3 },
  { preset: true, param: 'setcamexposurepreset', value: 2 },
  { preset: true, param: 'setcaminnerpreset', value: 3 },
  { param: 'setcammode', value: 2 },
  { param: 'setcamdetaillevel', value: 20 },
  { param: 'setcaminnerhori', value: 50 },
  { param: 'setcaminnervert', value: 50 },
  { param: 'setcamsmooth', value: 2 },
  { param: 'setcamsmoothenable', value: 0 },
  { param: 'setcamsmoothmaxframes', value: 5 },
  { param: 'setcamsmoothmaxdiff', value: 15 },
  { param: 'setcamperformance', value: 4 },
  { param: 'setcamres', value: 4 },
  { param: 'setcamfreq', value: 20 },
  { param: 'setcambufcount', value: 2 },
  { param: 'setcamflicker', value: 0 },
  { param: 'setcamquality', value: 6 },
  { param: 'setcamautoonoff', value: 0 },
  { param: 'setcamautoonoffdelay', value: 15 },
  { param: 'setcamcolorred', value: 100 },
  { param: 'setcamcolorgreen', value: 100 },
  { param: 'setcamcolorblue', value: 100 },
  { param: 'setcamactivationthreshold', value: 15 },
  { param: 'setcamblackthresholdsmooth', value: 2 },
  { param: 'setcamblackremovethreshold', value: 10 },
  { param: 'setcamminpixelamount', value: 5 },
  { param: 'setcamcontrast', value: 0 },
  { param: 'setcambrightness', value: 0 },
  { param: 'setcamsaturation', value: 0 },
  { param: 'setcamaelevels', value: 0 },
  { param: 'setcamquality', value: 6 },
  { param: 'setcamaecvalue', value: 1200 },
  { param: 'setcamagcgain', value: 0 },
  { param: 'setcamaecminvalue', value: 0 },
  { param: 'setcamaecmaxvalue', value: 1200 },
  { param: 'setcamwhiteactthreshold', value: 200 },
  { param: 'setcamadaptivechangepercent', value: 10 },
  { param: 'setcamwhiteminimumamount', value: 5 },
  { param: 'setcambeforewhiteactthreshold', value: 50 },
  { param: 'setcamadaptivechangedelay', value: 5 },
  { param: 'setcamadaptivegaindown', value: 20 },
  { param: 'setcamadaptivegainup', value: 20 },
  { param: 'setcamadaptivegainmax', value: 30 },
  { param: 'setcamagaincontrol', value: 1 },
  { param: 'setcamawhitebalance', value: 1 },
  { param: 'setcamawbgain', value: 1 },
  { param: 'setcamaec', value: 0 },
  { param: 'setcamaec2', value: 0 },
  { param: 'setcamadptexp', value: 0 },
  { param: 'setcamadptgain', value: 0 },
  { param: 'setcamhmirror', value: 0 },
  { param: 'setcamvflip', value: 0 },
  { param: 'setcamdetailsmooth', value: 0 },
  { param: 'setcamhighquality', value: 0 },
  { param: 'setcambpc', value: 1 },
  { param: 'setcamwpc', value: 1 },
  { param: 'setcamdenoise', value: 1 },
  { param: 'setcamlenc', value: 0 },
  { param: 'setcamrawgma', value: 1 },
  { param: 'setcamdcw', value: 1 },
  { param: 'setcamspecialeffect', value: 0 },
  { param: 'setcamwbmode', value: 2 },
]

export const HUE_DEFAULTS = [
  { preset: true, param: 'sethuepreset', value: 2 },
  { param: 'sethueframelength', value: 28 },
  { param: 'sethuehandshaketimeout', value: 10 },
]

export const DREAMSCREEN_DEFAULTS = [
  { param: 'setdreamscreensupport', value: 0 },
  { param: 'setdreamscreenemulation', value: 0 },
  { param: 'setdreamscreengroup', value: 0 },
  { param: 'setdreamscreencolorsmoothing', value: 0 },
]
